packages:
  - './*/*/*'

allowBuilds:
  '@parcel/watcher': false
  '@swc/core': true
  core-js: true
  core-js-pure: true
  sharp: false

overrides:
  '@typescript-eslint/parser': 8.59.3
  '@typescript-eslint/typescript-estree': 8.59.3
  event-target-shim: 6.0.2
  react-dom: 19.1.0
  react-native: 0.80.1
  react: 19.1.0

patchedDependencies:
  '@react-native-documents/picker': patches/@react-native-documents__picker.patch
  '@react-native/gradle-plugin': patches/@react-native__gradle-plugin.patch
  eslint-plugin-import: patches/eslint-plugin-import.patch
  eslint-plugin-react: patches/eslint-plugin-react.patch
  event-target-shim: patches/event-target-shim.patch
  jssip: patches/jssip.patch
  mobx-react: patches/mobx-react.patch
  react-native-callkeep: patches/react-native-callkeep.patch
  react-native-notifications: patches/react-native-notifications.patch
  react-native-splash-screen: patches/react-native-splash-screen.patch
  react-native-voip-push-notification: patches/react-native-voip-push-notification.patch
  react-native-web: patches/react-native-web.patch
  react-native-webrtc: patches/react-native-webrtc.patch
  react-native: patches/react-native.patch
