export const enforceUseClient = [
  'useState',
  'useEffect',
  'useRef',
  'createContext',
  'useContext',
  'useSyncExternalStore',
  'useImmer',
  'useClassState',
  'useRefConstruct',
  'useSafeContext',
  'useIsMounted',
  'useWindowDemensions',
  'useResponsiveState',
]
